-- MySQL Script generated by MySQL Workbench
-- 05/26/21 15:08:02
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tricount
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tricount` ;
CREATE SCHEMA IF NOT EXISTS `tricount` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tricount` ;

-- -----------------------------------------------------
-- Table `tricount`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tricount`.`contact` ;

CREATE TABLE IF NOT EXISTS `tricount`.`contact` (
  `id` INT NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tricount`.`contact` (`id` ASC);


-- -----------------------------------------------------
-- Table `tricount`.`expense_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tricount`.`expense_list` ;

CREATE TABLE IF NOT EXISTS `tricount`.`expense_list` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tricount`.`expense_list` (`id` ASC);


-- -----------------------------------------------------
-- Table `tricount`.`expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tricount`.`expense` ;

CREATE TABLE IF NOT EXISTS `tricount`.`expense` (
  `id` INT NOT NULL,
  `ownerid` INT NOT NULL,
  `expenselistid` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `amount` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ownerid`
    FOREIGN KEY (`ownerid`)
    REFERENCES `tricount`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expenselistid`
    FOREIGN KEY (`expenselistid`)
    REFERENCES `tricount`.`expense_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tricount`.`expense` (`id` ASC);

CREATE INDEX `ownerid_idx` ON `tricount`.`expense` (`ownerid` ASC);

CREATE INDEX `expenselistid_idx` ON `tricount`.`expense` (`expenselistid` ASC);


-- -----------------------------------------------------
-- Table `tricount`.`contact_expense_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tricount`.`contact_expense_list` ;

CREATE TABLE IF NOT EXISTS `tricount`.`contact_expense_list` (
  `id` INT NOT NULL,
  `contactid` INT NOT NULL,
  `expenselistid` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `contactid`
    FOREIGN KEY (`contactid`)
    REFERENCES `tricount`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expenselistid`
    FOREIGN KEY (`expenselistid`)
    REFERENCES `tricount`.`expense_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tricount`.`contact_expense_list` (`id` ASC);

CREATE INDEX `contactid_idx` ON `tricount`.`contact_expense_list` (`contactid` ASC);

CREATE INDEX `expenselistid_idx` ON `tricount`.`contact_expense_list` (`expenselistid` ASC);


-- -----------------------------------------------------
-- Table `tricount`.`beneficiary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tricount`.`beneficiary` ;

CREATE TABLE IF NOT EXISTS `tricount`.`beneficiary` (
  `id` INT NOT NULL,
  `expenseid` INT NOT NULL,
  `contactid` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `expenseid`
    FOREIGN KEY (`expenseid`)
    REFERENCES `tricount`.`expense` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contactid`
    FOREIGN KEY (`contactid`)
    REFERENCES `tricount`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `tricount`.`beneficiary` (`id` ASC);

CREATE INDEX `expenseid_idx` ON `tricount`.`beneficiary` (`expenseid` ASC);

CREATE INDEX `contactid_idx` ON `tricount`.`beneficiary` (`contactid` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
